### PR TITLE
New db functions added to retrieve data.

### PR DESCRIPTION
**Pull request by Sach24eth**
New db functions were added to retrieve data.
Would appreciate any help in testing this. Will continue testing the PR for more bugs for today.
- CSS of the chatroom needs to be changed. Will do this
- Will still be testing for bugs

### CODE REVIEW

**Review by tejasraibagi26 — CHANGES_REQUESTED** [review]
Few things we could change:

1. Only show SpotBot user joined message if the user has newly joined the chatroom. 
2. Add a simple Spinner (the component already exist) while retrieving data from db
3. Leaving the chatroom gives error on the server and is not handled on the client `ReferenceError: uid is not defined
    at Object.leaveChatroom`

**Comment by Sach24eth** [comment]
Are you sure about number point number 1?
Cuz users will not know if the user has joined the chat in the first place itself after they join a chatroom initally? 3 is solved and I will be pushing the change soon

**Comment by tejasraibagi26** [comment]
> Are you sure about number point number 1?
> 
> Cuz users will not know if the user has joined the chat in the first place itself after they join a chatroom initally? 3 is solved and I will be pushing the change soon

1st point is your choice. I recommended that coz most chat app only shows the message of joining once. But it's not a major requirement.

**Comment by Sach24eth** [comment]
Submitted another change
1) Eliminated error popping up while searching for chatroom in homepage. "Type error" fixed.

**Review by tejasraibagi26 — APPROVED** [review]

**Comment by tejasraibagi26** [comment]
Good to go.

**Pull request merged**
